
[env]
GM_MCTRL_ARCHIVE_DIR = { value = "ext/archives", relative = true, force = true }
GM_MCTRL_TOOLCHAIN_DIR = { value = "ext/toolchains", relative = true, force = true }

[registries]
crates-io = { index = "https://github.com/rust-lang/crates.io-index" }
globus = { index = "sparse+https://globus.jfrog.io/artifactory/api/cargo/globus-cargo-local/index/" }
